// <auto-generated />
namespace BJProduction.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nov7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nov7));
        
        string IMigrationMetadata.Id
        {
            get { return "202111071254194_nov7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
