// <auto-generated />
namespace BJProduction.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Location_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Location_type));
        
        string IMigrationMetadata.Id
        {
            get { return "202211080955442_Location_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
