// <auto-generated />
namespace BJProduction.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class feature_Unitmeasurement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(feature_Unitmeasurement));
        
        string IMigrationMetadata.Id
        {
            get { return "202211170715072_feature_Unitmeasurement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
