// <auto-generated />
namespace BJProduction.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class salesextv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(salesextv2));
        
        string IMigrationMetadata.Id
        {
            get { return "202302242130153_salesextv2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
